# This file is part of AUSBEE.
#
# Copyright (C) 2015 AUSBEE Developers <ausbee@googlegroups.com>
#
# AUSBEE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# AUSBEE is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with AUSBEE.  If not, see <http://www.gnu.org/licenses/>.

STM32F4XX_STDPERIPH_DRIVER_PATH=$(PACKAGES_PATH)/stm32f4xx_stdperiph_driver
STM32F4XX_STDPERIPH_DRIVER_SRC_PATH=$(STM32F4XX_STDPERIPH_DRIVER_PATH)/src

# Include files
STM32F4XX_STDPERIPH_DRIVER_INCLUDES=-I"$(STM32F4XX_STDPERIPH_DRIVER_PATH)/inc"
# Add the include directory to the libraries include dir
PACKAGES_INCLUDES+=$(STM32F4XX_STDPERIPH_DRIVER_INCLUDES)

# Source files
ifeq ($(CONFIG_STM32F4XX_STDPERIPH_DRIVER_CAN),y)
STM32F4XX_STDPERIPH_DRIVER_SRC_FILES+=$(STM32F4XX_STDPERIPH_DRIVER_SRC_PATH)/stm32f4xx_can.c
endif
ifeq ($(CONFIG_STM32F4XX_STDPERIPH_DRIVER_ADC),y)
STM32F4XX_STDPERIPH_DRIVER_SRC_FILES+=$(STM32F4XX_STDPERIPH_DRIVER_SRC_PATH)/stm32f4xx_adc.c
endif
ifeq ($(CONFIG_STM32F4XX_STDPERIPH_DRIVER_RCC),y)
STM32F4XX_STDPERIPH_DRIVER_SRC_FILES+=$(STM32F4XX_STDPERIPH_DRIVER_SRC_PATH)/stm32f4xx_rcc.c
endif
ifeq ($(CONFIG_STM32F4XX_STDPERIPH_DRIVER_GPIO),y)
STM32F4XX_STDPERIPH_DRIVER_SRC_FILES+=$(STM32F4XX_STDPERIPH_DRIVER_SRC_PATH)/stm32f4xx_gpio.c
endif
ifeq ($(CONFIG_STM32F4XX_STDPERIPH_DRIVER_TIM),y)
STM32F4XX_STDPERIPH_DRIVER_SRC_FILES+=$(STM32F4XX_STDPERIPH_DRIVER_SRC_PATH)/stm32f4xx_tim.c
endif
ifeq ($(CONFIG_STM32F4XX_STDPERIPH_DRIVER_USART),y)
STM32F4XX_STDPERIPH_DRIVER_SRC_FILES+=$(STM32F4XX_STDPERIPH_DRIVER_SRC_PATH)/stm32f4xx_usart.c
endif
ifeq ($(CONFIG_STM32F4XX_STDPERIPH_SPI),y)
STM32F4XX_STDPERIPH_DRIVER_SRC_FILES+=$(STM32F4XX_STDPERIPH_DRIVER_SRC_PATH)/stm32f4xx_spi.c
endif
ifeq ($(CONFIG_STM32F4XX_STDPERIPH_EXTI),y)
STM32F4XX_STDPERIPH_DRIVER_SRC_FILES+=$(STM32F4XX_STDPERIPH_DRIVER_SRC_PATH)/stm32f4xx_exti.c
endif
ifeq ($(CONFIG_STM32F4XX_STDPERIPH_SYSCFG),y)
STM32F4XX_STDPERIPH_DRIVER_SRC_FILES+=$(STM32F4XX_STDPERIPH_DRIVER_SRC_PATH)/stm32f4xx_syscfg.c
endif
ifeq ($(CONFIG_STM32F4XX_STDPERIPH_MISC),y)
STM32F4XX_STDPERIPH_DRIVER_SRC_FILES+=$(STM32F4XX_STDPERIPH_DRIVER_SRC_PATH)/misc.c
endif
#TODO add others

# Object files list
STM32F4XX_STDPERIPH_DRIVER_OBJ_FILES=$(STM32F4XX_STDPERIPH_DRIVER_SRC_FILES:.c=.o)
STM32F4XX_STDPERIPH_DRIVER_OBJ_FILES=$(patsubst ${AUSBEE_DIR}/%.c,${OUTPUT_PATH}/%.o,${STM32F4XX_STDPERIPH_DRIVER_SRC_FILES})

# Add the object files to the global object files list
OBJ_FILES+=$(STM32F4XX_STDPERIPH_DRIVER_OBJ_FILES)

# Build objects
$(STM32F4XX_STDPERIPH_DRIVER_OBJ_FILES): ${OUTPUT_PATH}/%.o :${AUSBEE_DIR}/%.c $(TOOLCHAIN_EXTRACTED)
	@mkdir -p $(dir $@)
	$(HOST_CC) -o $@ $(HOST_CFLAGS) $(STM32F4XX_STDPERIPH_DRIVER_INCLUDES) $(SYSTEM_INCLUDES) $(HOST_OPTIMISATION) -c $<
