$(LIBAUSBEE_DONE):
#	$(MKDIR_P) $(LIBAUSBEE_BUILD_PATH)
#	$(CD) $(LIBAUSBEE_BUILD_PATH) ; \
#	PATH=$(CONFIG_TOOLCHAIN_PATH):$(PATH) ; \
#	$(CONFIG_LIBAUSBEE_SRC_DIR)/configure --prefix=$(OUTPUT_TARGET_PATH) \
#	 --target=$(CONFIG_TOOLCHAIN_TARGET_NAME) --host=$(CONFIG_TOOLCHAIN_TARGET_NAME) CFLAGS=$(CONFIG_TOOLCHAIN_CFLAGS) ; \
#	$(MAKE) -C $(LIBAUSBEE_BUILD_PATH) ; $(MAKE) -C $(LIBAUSBEE_BUILD_PATH) install
#	$(TOUCH) $@
