# Path
FREERTOS_SRC_PATH=$(subst $(DQUOTE),,$(SRC_PATH)/FreeRTOSV$(CONFIG_FREERTOS_VERSION_DOWNLOAD))
ARCHIVE_FREERTOS_PATH=$(subst $(DQUOTE),,$(CONFIG_DOWNLOADS_DIR)/FreeRTOSV$(CONFIG_FREERTOS_VERSION_DOWNLOAD).zip)
# TODO make it configurable
FREERTOS_SRC_PORT_PATH=$(FREERTOS_SRC_PATH)/FreeRTOS/Source/portable/GCC/ARM_CM3

# Extract files
$(FREERTOS_SRC_PATH)/.extracted:$(ARCHIVE_FREERTOS_PATH)
	$(UNZIP) -d $(SRC_PATH) $<
	$(TOUCH) $@

#TODO ifeq for choosing if FreeRTOS must be downloaded or not
# Download requested files
$(ARCHIVE_FREERTOS_PATH):
	$(MKDIR_P) $(CONFIG_DOWNLOADS_DIR)
	$(WGET) -O $@ $(CONFIG_FREERTOS_URL_DOWNLOAD)
