PLATFORM_STM32F4DISCOVERY=$(PLATFORMS_PATH)/stm32f4discovery

PLATFORMS_INCLUDES_DIR=-I"$(PLATFORM_STM32F4DISCOVERY)"

PLATFORM_SRC_FILES+=$(PLATFORM_STM32F4DISCOVERY)/platform.c
PLATFORM_SRC_FILES+=$(PLATFORM_STM32F4DISCOVERY)/stm32f4_discovery_lis302dl.c
PLATFORM_OBJ_FILES=$(PLATFORM_SRC_FILES:.c=.o)

OBJ_FILES+=$(PLATFORM_OBJ_FILES)

$(PLATFORM_OBJ_FILES): %.o :%.c $(TOOLCHAIN_EXTRACTED)
	$(HOST_CC) -o $@ $(HOST_CFLAGS) $(LIBRARIES_INCLUDES_DIR) $(SYSTEM_INCLUDES_DIR) $(HOST_OPTIMISATION) -c $<

.PHONY:platform_stm32f4discovery-clean
platform_stm32f4discovery-clean:
	$(RM_RF) $(OBJ_FILES)
