CMSIS_DEVICE_SUPPORT_PATH=$(SYSTEM_PATH)/CMSIS/CM3/DeviceSupport/ST/STM32F10x
CMSIS_CORE_SUPPORT_PATH=$(SYSTEM_PATH)/CMSIS/CM3/CoreSupport

LINKER_SCRIPT_PATH=$(SYSTEM_PATH)/link.ld

SYSTEM_INCLUDES_DIR=-I"$(CMSIS_DEVICE_SUPPORT_PATH)"
SYSTEM_INCLUDES_DIR+=-I"$(CMSIS_CORE_SUPPORT_PATH)"
SYSTEM_INCLUDES_DIR+=-I"$(SYSTEM_PATH)/include"

SYSTEM_SRC_FILES=$(CMSIS_CORE_SUPPORT_PATH)/core_cm3.c
SYSTEM_SRC_FILES+=$(CMSIS_DEVICE_SUPPORT_PATH)/system_stm32f10x.c
#SYSTEM_SRC_FILES+=$(SYSTEM_PATH)/startup.c
SYSTEM_SRC_FILES+=$(SYSTEM_PATH)/syscalls.c
SYSTEM_S_SRC_FILES+=$(CMSIS_DEVICE_SUPPORT_PATH)/startup/gcc_ride7/startup_stm32f10x_ld.s

ifeq ($(CONFIG_STM32F10X_STDPERIPH_DRIVER),y)
SYSTEM_SRC_FILES+=$(SYSTEM_PATH)/stm32f10x_conf.c
endif

# Object files list
SYSTEM_OBJ_FILES=$(SYSTEM_SRC_FILES:.c=.o)
SYSTEM_S_OBJ_FILES=$(SYSTEM_S_SRC_FILES:.s=.o)

# Build objects
$(SYSTEM_OBJ_FILES): %.o :%.c $(TOOLCHAIN_EXTRACTED)
	$(HOST_CC) -o $@ $(HOST_CFLAGS) $(SYSTEM_INCLUDES_DIR) -c $<

$(SYSTEM_S_OBJ_FILES): %.o :%.s $(TOOLCHAIN_EXTRACTED)
	$(HOST_CC) -o $@ $(HOST_CFLAGS) $(SYSTEM_INCLUDES_DIR) -c $<

.PHONY: system-clean
system-clean:
	$(RM_RF) $(SYSTEM_OBJ_FILES)

