LIBAUSBEE_PATH=$(LIBRARIES_PATH)/libausbee
LIBAUSBEE_SRC_PATH=$(LIBAUSBEE_PATH)/src

# Include files
LIBAUSBEE_INC_PATH=-I"$(LIBAUSBEE_PATH)/include/"

# Add the include directory to the libraries include dir
LIBRARIES_INCLUDES_DIR+=$(LIBAUSBEE_INC_PATH)

# Retrieve StdPeriph includes
ifeq ($(CONFIG_STM32F4XX_STDPERIPH_DRIVER),y)
STD_PERIPH_INCLUDES_DIR=$(STM32F4XX_STDPERIPH_DRIVER_INC_PATH)
endif
ifeq ($(CONFIG_STM32F10X_STDPERIPH_DRIVER),y)
STD_PERIPH_INCLUDES_DIR=$(STM32F10X_STDPERIPH_DRIVER_INC_PATH)
endif

# Add source files
ifeq ($(CONFIG_LIBAUSBEE_LIDAR),y)
LIBAUSBEE_SRC_FILES+=$(LIBAUSBEE_SRC_PATH)/lidar/lidar.c
endif

ifeq ($(CONFIG_LIBAUSBEE_L298_DRIVER),y)
LIBAUSBEE_SRC_FILES+=$(LIBAUSBEE_SRC_PATH)/l298_driver/l298_driver.c
endif

ifeq ($(CONFIG_LIBAUSBEE_ENCODER),y)
LIBAUSBEE_SRC_FILES+=$(LIBAUSBEE_SRC_PATH)/encoder/encoder.c
endif

ifeq ($(CONFIG_LIBAUSBEE_SERVO),y)
LIBAUSBEE_SRC_FILES+=$(LIBAUSBEE_SRC_PATH)/servo/servo.c
endif

ifeq ($(CONFIG_LIBAUSBEE_AX12),y)
LIBAUSBEE_SRC_FILES+=$(LIBAUSBEE_SRC_PATH)/ax12/ax12.c
endif

ifeq ($(CONFIG_LIBAUSBEE_CONTROLLER),y)
LIBAUSBEE_SRC_FILES+=$(LIBAUSBEE_SRC_PATH)/control_system/controller/pid.c
endif

# Object files list
LIBAUSBEE_OBJ_FILES=$(LIBAUSBEE_SRC_FILES:.c=.o)

# Add the object files to the global object files
OBJ_FILES+=$(LIBAUSBEE_OBJ_FILES)

# Build objects
$(LIBAUSBEE_OBJ_FILES): %.o :%.c $(TOOLCHAIN_EXTRACTED)
	$(HOST_CC) -o $@ $(HOST_CFLAGS) $(LIBAUSBEE_INC_PATH) $(STD_PERIPH_INCLUDES_DIR) $(SYSTEM_INCLUDES_DIR) $(HOST_OPTIMISATION) -c $<

.PHONY: libausbee-clean libausbee-doc

libausbee-doc:
	$(CD) $(DOCUMENTATION_PATH)/libausbee ; \
	$(DOXYGEN) $(DOCUMENTATION_PATH)/libausbee/Doxyfile

libausbee-clean:
	$(RM_RF) $(LIBAUSBEE_OBJ_FILES)
