CMSIS_CM3_DEVICE_SUPPORT_PATH=$(SYSTEM_PATH)/CMSIS/CM3/DeviceSupport/ST/STM32F10x/
CMSIS_CM3_CORE_SUPPORT_PATH=$(SYSTEM_PATH)/CMSIS/CM3/CoreSupport

LINKER_SCRIPT_PATH=$(SYSTEM_PATH)/link.ld

# In case of CortexM3
#TODO add case of CortexM4
SYSTEM_INCLUDES_DIR=-I"$(CMSIS_CM3_DEVICE_SUPPORT_PATH)"
SYSTEM_INCLUDES_DIR+=-I"$(CMSIS_CM3_CORE_SUPPORT_PATH)"

# In case of CortexM3
#TODO add case of CortexM4
SYSTEM_SRC_FILES=$(CMSIS_CM3_CORE_SUPPORT_PATH)/core_cm3.c
SYSTEM_SRC_FILES+=$(CMSIS_CM3_DEVICE_SUPPORT_PATH)/system_stm32f10x.c
SYSTEM_SRC_FILES+=$(SYSTEM_PATH)/startup.c
SYSTEM_SRC_FILES+=$(SYSTEM_PATH)/syscalls.c

# Object files list
SYSTEM_OBJ_FILES=$(SYSTEM_SRC_FILES:.c=.o)

# Build objects
$(SYSTEM_OBJ_FILES): %.o :%.c
	$(HOST_CC) -o $@ $(HOST_CFLAGS) $(SYSTEM_INCLUDES_DIR) -c $<

.PHONY: system-clean
system-clean:
	$(RM_RF) $(SYSTEM_OBJ_FILES)

