PLATFORM_STM32F4DISCOVERY=$(PLATFORMS_PATH)/stm32f4discovery

PLATFORMS_INCLUDES_DIR=-I"$(PLATFORM_STM32F4DISCOVERY)"

PLATFORM_SRC_FILES+=$(PLATFORM_STM32F4DISCOVERY)/platform.c
PLATFORM_SRC_FILES+=$(PLATFORM_STM32F4DISCOVERY)/stm32f4_discovery_lis302dl.c
PLATFORM_OBJ_FILES=$(patsubst ${AUSBEE_DIR}/%.c,${OUTPUT_PATH}/%.o,${PLATFORM_SRC_FILES})

OBJ_FILES+=$(PLATFORM_OBJ_FILES)

$(PLATFORM_OBJ_FILES): $(OUTPUT_PATH)/%.o :$(AUSBEE_DIR)/%.c $(TOOLCHAIN_EXTRACTED)
	@mkdir -p $(dir $@)
	$(HOST_CC) -o $@ $(HOST_CFLAGS) $(LIBRARIES_INCLUDES_DIR) $(SYSTEM_INCLUDES_DIR) $(HOST_OPTIMISATION) -c $<

.PHONY:platform_stm32f4discovery-clean
platform_stm32f4discovery-clean:
	$(RM_RF) $(OBJ_FILES)
