STM32F4XX_STDPERIPH_DRIVER_PATH=$(LIBRARIES_PATH)/STM32F4xx_StdPeriph_Driver
STM32F4XX_STDPERIPH_DRIVER_SRC_PATH=$(STM32F4XX_STDPERIPH_DRIVER_PATH)/src

# Include files
STM32F4XX_STDPERIPH_DRIVER_INC_PATH=-I"$(STM32F4XX_STDPERIPH_DRIVER_PATH)/inc"

# Add the include directory to the libraries include dir
LIBRARIES_INCLUDES_DIR+=$(STM32F4XX_STDPERIPH_DRIVER_INC_PATH)

# Source files
ifeq ($(CONFIG_STM32F4XX_STDPERIPH_DRIVER_CAN),y)
STM32F4XX_STDPERIPH_DRIVER_SRC_FILES+=$(STM32F4XX_STDPERIPH_DRIVER_SRC_PATH)/stm32f4xx_can.c
endif
ifeq ($(CONFIG_STM32F4XX_STDPERIPH_DRIVER_RCC),y)
STM32F4XX_STDPERIPH_DRIVER_SRC_FILES+=$(STM32F4XX_STDPERIPH_DRIVER_SRC_PATH)/stm32f4xx_rcc.c
endif
ifeq ($(CONFIG_STM32F4XX_STDPERIPH_DRIVER_GPIO),y)
STM32F4XX_STDPERIPH_DRIVER_SRC_FILES+=$(STM32F4XX_STDPERIPH_DRIVER_SRC_PATH)/stm32f4xx_gpio.c
endif
ifeq ($(CONFIG_STM32F4XX_STDPERIPH_DRIVER_TIM),y)
STM32F4XX_STDPERIPH_DRIVER_SRC_FILES+=$(STM32F4XX_STDPERIPH_DRIVER_SRC_PATH)/stm32f4xx_tim.c
endif
ifeq ($(CONFIG_STM32F4XX_STDPERIPH_DRIVER_USART),y)
STM32F4XX_STDPERIPH_DRIVER_SRC_FILES+=$(STM32F4XX_STDPERIPH_DRIVER_SRC_PATH)/stm32f4xx_usart.c
endif
ifeq ($(CONFIG_STM32F4XX_STDPERIPH_MISC),y)
STM32F4XX_STDPERIPH_DRIVER_SRC_FILES+=$(STM32F4XX_STDPERIPH_DRIVER_SRC_PATH)/misc.c
endif
#TODO add others

# Object files list
STM32F4XX_STDPERIPH_DRIVER_OBJ_FILES=$(STM32F4XX_STDPERIPH_DRIVER_SRC_FILES:.c=.o)

# Add the object files to the global object files list
OBJ_FILES+=$(STM32F4XX_STDPERIPH_DRIVER_OBJ_FILES)

# Build objects
$(STM32F4XX_STDPERIPH_DRIVER_OBJ_FILES): %.o :%.c $(TOOLCHAIN_EXTRACTED)
	$(HOST_CC) -o $@ $(HOST_CFLAGS) $(STM32F4XX_STDPERIPH_DRIVER_INC_PATH) $(SYSTEM_INCLUDES_DIR) $(HOST_OPTIMISATION) -c $<

.PHONY:stm32f4xx_stdperiph_driver-clean stm32f4xx_stdperiph_driver-doc

stm32f4xx_stdperiph_driver-doc:
	$(CD) $(DOCUMENTATION_PATH)/STM32F4xx_StdPeriph_Driver ; \
	$(DOXYGEN) $(DOCUMENTATION_PATH)/STM32F4xx_StdPeriph_Driver/Doxyfile

stm32f4xx_stdperiph_driver-clean:
	$(RM_RF) $(STM32F4XX_STDPERIPH_DRIVER_OBJ_FILES)
