FREERTOS_PATH=$(subst $(DQUOTE),,$(BUILD_PATH)/FreeRTOSV$(CONFIG_FREERTOS_VERSION_DOWNLOAD))
# TODO make it configurable
FREERTOS_PORT_PATH=$(FREERTOS_PATH)/FreeRTOS/Source/portable/GCC/ARM_CM3
FREERTOS_DONE=$(FREERTOS_PATH)/.done
