PROJECT_INCLUDES_DIR = $(FREERTOS_INCLUDES_DIR) # Add FREERTOS include files
PROJECT_INCLUDES_DIR += $(PLATFORMS_INCLUDES_DIR)
PROJECT_INCLUDES_DIR += $(LIBRARIES_INCLUDES_DIR)
PROJECT_INCLUDES_DIR += $(SYSTEM_INCLUDES_DIR)

PROJECT_SRC_FILES=$(wildcard $(PROJECT_PATH)/src/*.c)
PROJECT_OBJ_FILES=$(patsubst %.c,%.o,${PROJECT_SRC_FILES})

# Add project obj files to the global obj files list
OBJ_FILES+=$(PROJECT_OBJ_FILES)


$(OUTPUT_TARGET_HEX): $(OUTPUT_TARGET_ELF)
	$(HOST_OBJCPY) -O ihex $^ $@
	$(HOST_SIZE) $@

$(OUTPUT_TARGET_ELF): 	$(OBJ_FILES) $(LINKER_SCRIPT)
	$(MKDIR_P) $(OUTPUT_PATH)
	$(HOST_CC) -o $@ $(HOST_LDFLAGS) -T$(LINKER_SCRIPT) 	$(OBJ_FILES) \

$(PROJECT_OBJ_FILES): %.o: %.c $(PROJECT_DEPENDENCIES) $(TOOLCHAIN_EXTRACTED)
	$(HOST_CC) -o $@ $(HOST_CFLAGS) $(PROJECT_INCLUDES_DIR) $(HOST_OPTIMISATION) -c $<

.PHONY:project-clean
project-clean:
	$(RM_RF) $(PROJECT_OBJ_FILES) $(OUTPUT_TARGET_HEX) $(OUTPUT_TARGET_ELF)
