TOOLCHAIN_ARCHIVE=$(subst $(DQUOTE),,$(CONFIG_DOWNLOADS_DIR)/$(TOOLCHAIN_ARCHIVE_NAME))

$(TOOLCHAIN_EXTRACTED): $(TOOLCHAIN_ARCHIVE)
	$(MKDIR_P) $(TOOLCHAIN_EXTRACTED_PATH)
	tar xvf $< -C $(TOOLCHAIN_EXTRACTED_PATH) --strip-components=1
	touch $@

$(TOOLCHAIN_ARCHIVE):
	$(MKDIR_P) $(CONFIG_DOWNLOADS_DIR)
	$(WGET) -O $@ $(CONFIG_TOOLCHAIN_MIRROR)

toolchain-dirclean:
	$(RM_RF) $(TOOLCHAIN_EXTRACTED_PATH) $(TOOLCHAIN_EXTRACTED)
